# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  dinner@v1: 
    root: openapi/openapi.yaml
  dinner@v2:
    root: openapi/v2.yaml
lint:
  extends:
    - recommended
  rules:
    operation-4xx-response: off
features.openapi:
  htmlTemplate: ./docs/index.html
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: "Node.js"
      - lang: "JavaScript"
      - lang: Python
      - lang: PHP
      - lang: Java
      - lang: C#