# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  dinner: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
referenceDocs:
  htmlTemplate: ./docs/index.html
  # theme:
  #   colors:
      # primary:
      #   main: "#32329f"
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl # Can be one of the following supported languages: "curl", "Node.js", "JavaScript".
      - lang: "Node.js"
      - lang: "JavaScript"
      - lang: Python
      - lang: Java
      - lang: C#